package chat

import "PMAS/internal/domain/shared"

var (
	ErrConversationNotFound     = shared.New("CHAT_CONVERSATION_NOT_FOUND", "Conversation not found", 404)
	ErrMessageNotFound          = shared.New("CHAT_MESSAGE_NOT_FOUND", "Message not found", 404)
	ErrMemberNotFound           = shared.New("CHAT_MEMBER_NOT_FOUND", "Conversation member not found", 404)
	ErrInvalidConversationType  = shared.New("CHAT_INVALID_CONVERSATION_TYPE", "Invalid conversation type", 400)
	ErrInvalidVisibility        = shared.New("CHAT_INVALID_VISIBILITY", "Invalid channel visibility", 400)
	ErrInvalidMessageType       = shared.New("CHAT_INVALID_MESSAGE_TYPE", "Invalid message type", 400)
	ErrInvalidContentFormat     = shared.New("CHAT_INVALID_CONTENT_FORMAT", "Invalid content format", 400)
	ErrMessageBodyRequired      = shared.New("CHAT_MESSAGE_BODY_REQUIRED", "Message content is required", 400)
	ErrMessageTooLong           = shared.New("CHAT_MESSAGE_TOO_LONG", "Message exceeds maximum length", 400)
	ErrInvalidMemberRole        = shared.New("CHAT_INVALID_MEMBER_ROLE", "Invalid member role", 400)
	ErrInvalidNotificationLevel = shared.New("CHAT_INVALID_NOTIFICATION_LEVEL", "Invalid notification level", 400)
	ErrInvalidPresenceStatus    = shared.New("CHAT_INVALID_PRESENCE_STATUS", "Invalid presence status", 400)
	ErrInvalidMentionType       = shared.New("CHAT_INVALID_MENTION_TYPE", "Invalid mention type", 400)
	ErrInvalidReportReason      = shared.New("CHAT_INVALID_REPORT_REASON", "Invalid report reason", 400)
	ErrInvalidReportStatus      = shared.New("CHAT_INVALID_REPORT_STATUS", "Invalid report status", 400)
	ErrInvalidInvitationStatus  = shared.New("CHAT_INVALID_INVITATION_STATUS", "Invalid invitation status", 400)
	ErrInvalidReactionEmoji     = shared.New("CHAT_INVALID_REACTION_EMOJI", "Invalid reaction emoji", 400)
	ErrInvalidCursor            = shared.New("CHAT_INVALID_CURSOR", "Invalid pagination cursor", 400)
	ErrSearchQueryTooShort      = shared.New("CHAT_SEARCH_QUERY_TOO_SHORT", "Search query too short", 400)
	ErrNotificationNotFound     = shared.New("CHAT_NOTIFICATION_NOT_FOUND", "Notification not found", 404)
	ErrDraftNotFound            = shared.New("CHAT_DRAFT_NOT_FOUND", "Draft not found", 404)
	ErrDraftConflict            = shared.New("CHAT_DRAFT_CONFLICT", "Draft was modified concurrently", 409)
	ErrPresenceNotFound         = shared.New("CHAT_PRESENCE_NOT_FOUND", "Presence not found", 404)
	ErrInvitationNotFound       = shared.New("CHAT_INVITATION_NOT_FOUND", "Invitation not found", 404)
	ErrInvitationExpired        = shared.New("CHAT_INVITATION_EXPIRED", "Invitation expired", 410)
	ErrInvitationNotPending     = shared.New("CHAT_INVITATION_NOT_PENDING", "Invitation is not pending", 409)
	ErrReportNotFound           = shared.New("CHAT_REPORT_NOT_FOUND", "Report not found", 404)
	ErrLastOwner                = shared.New("CHAT_LAST_OWNER", "Cannot remove or demote the last owner", 409)
	ErrOwnerCannotLeave         = shared.New("CHAT_OWNER_CANNOT_LEAVE", "Transfer ownership before leaving", 409)
	ErrBlocked                  = shared.New("CHAT_BLOCKED", "Messaging blocked between users", 403)
	ErrInvalidRoleChange        = shared.New("CHAT_INVALID_ROLE_CHANGE", "Invalid role change", 400)
	ErrCompanyRequired          = shared.New("CHAT_COMPANY_REQUIRED", "Company is required", 400)
	ErrConversationRequired     = shared.New("CHAT_CONVERSATION_REQUIRED", "Conversation is required", 400)
	ErrEmployeeRequired         = shared.New("CHAT_EMPLOYEE_REQUIRED", "Employee is required", 400)
)
