import type { AppState } from "./types";

export const initialAppState: AppState = {
  currentView: "executive",
  user: {
    name: "Sarah Jenkins",
    role: "VP of Product & Architecture",
    avatarText: "SJ",
    email: "sarah.jenkins@enterprise.pmas.com",
    department: "Product Management & Architecture",
    bio: "Overseeing enterprise architectural compliance, security gateways, and cross-functional operations.",
    avatarColor:
      "linear-gradient(135deg, var(--color-primary), var(--color-info))",
  },
  settings: {
    notificationAlerts: true,
    simulationSpeed: "normal",
    complianceThreshold: 75,
    compactMode: false,
    sidebarCollapsed: false,
  },
  credentials: [],
  complianceChecklist: [
    {
      id: "gdpr-inventory",
      category: "GDPR",
      text: "Register GDPR Data Inventory & mapping",
      checked: true,
    },
    {
      id: "gdpr-privacy",
      category: "GDPR",
      text: "Deploy updated Privacy Policy & Consent forms",
      checked: true,
    },
    {
      id: "gdpr-dpo",
      category: "GDPR",
      text: "Appoint EU Data Protection Officer (DPO)",
      checked: false,
    },
    {
      id: "ccpa-dns",
      category: "CCPA",
      text: 'Implement "Do Not Sell My Info" link',
      checked: true,
    },
    {
      id: "ccpa-delete",
      category: "CCPA",
      text: "Deploy CCPA customer data deletion pipelines",
      checked: false,
    },
    {
      id: "soc2-encryption",
      category: "SOC2",
      text: "Enable database encryption-at-rest for production",
      checked: true,
    },
    {
      id: "soc2-audit",
      category: "SOC2",
      text: "Complete external SOC2 Type II audit dry-run",
      checked: false,
    },
    {
      id: "hipaa-audit",
      category: "HIPAA",
      text: "Execute HIPAA access log audit verification",
      checked: false,
    },
  ],
  workspaceItems: [
    {
      id: "item-1",
      type: "blocker",
      title: "API Gateway Rate-Limiting Auth Loop",
      severity: "Critical",
      workspace: "infrastructure",
      owner: "Infra Team",
      status: "Blocked",
      details:
        "API Gateway auth loops under high load conditions. Investigate rate limit configurations on node ingress gateways.",
      createdAt: "2026-06-27T12:00:00Z",
    },
    {
      id: "item-2",
      type: "blocker",
      title: "Legal review on OAuth2 user-consent screen",
      severity: "High",
      workspace: "legalhr",
      owner: "Legal Team",
      status: "Blocked",
      details:
        "OAuth2 authorization screen requires compliance approval from legal counsel before deployment to production environment.",
      createdAt: "2026-06-27T12:10:00Z",
    },
    {
      id: "item-3",
      type: "blocker",
      title: "Figma token integration mismatch in theme engine",
      severity: "Medium",
      workspace: "uiux",
      owner: "UI/UX Team",
      status: "Blocked",
      details:
        "Mismatch in exported color token variables causing compilation warnings in themes and webpack build errors.",
      createdAt: "2026-06-27T12:20:00Z",
    },
    {
      id: "item-4",
      type: "blocker",
      title: "Database migration lockup on staging DB",
      severity: "Critical",
      workspace: "engineering",
      owner: "Engineering Core",
      status: "Blocked",
      details:
        "Prisma schema migration locked on database nodes. Needs DBA script intervention and lock release execution.",
      createdAt: "2026-06-27T12:30:00Z",
    },
    {
      id: "item-5",
      type: "blocker",
      title: "GDPR compliance signoff on analytic scripts",
      severity: "High",
      workspace: "legalhr",
      owner: "Legal Team",
      status: "Blocked",
      details:
        "GDPR compliance validation requested for newly integrated third-party client analytics script tracking behaviors.",
      createdAt: "2026-06-27T12:40:00Z",
    },
    {
      id: "item-6",
      type: "blocker",
      title: "CI/CD runner concurrency limit exhaustion",
      severity: "Medium",
      workspace: "infrastructure",
      owner: "Infra Team",
      status: "Blocked",
      details:
        "CI/CD runner node resource allocation limit reached. Increase concurrency caps and provision extra runner nodes.",
      createdAt: "2026-06-27T12:50:00Z",
    },
    {
      id: "item-7",
      type: "blocker",
      title: "Finance Q2 CapEx final reconciliation delay",
      severity: "Low",
      workspace: "finance",
      owner: "Finance Team",
      status: "Blocked",
      details:
        "Finance team report on Q2 CapEx ledger reconciliation delayed. Waiting for final hardware invoice imports from cloud provider vendors.",
      createdAt: "2026-06-27T13:00:00Z",
    },
    {
      id: "item-8",
      type: "task",
      title: "Refactor typography token parser",
      severity: "Low",
      workspace: "uiux",
      owner: "Elena R.",
      status: "In Progress",
      details:
        "Streamline the typography token JSON extraction process to align with our latest Figma token scheme.",
      createdAt: "2026-06-27T13:05:00Z",
    },
    {
      id: "item-9",
      type: "task",
      title: "Design landing page dark/light toggles",
      severity: "Medium",
      workspace: "uiux",
      owner: "Elena R.",
      status: "Backlog",
      details:
        "Draft alternative variants of visual themes for landing page user custom preferences.",
      createdAt: "2026-06-27T13:10:00Z",
    },
    {
      id: "item-10",
      type: "task",
      title: "Optimize query index on users table",
      severity: "High",
      workspace: "engineering",
      owner: "Marcus A.",
      status: "In Progress",
      details:
        "Add composited index on tenant_id and email fields to reduce peak latency of user auth queries.",
      createdAt: "2026-06-27T13:15:00Z",
    },
    {
      id: "item-11",
      type: "task",
      title: "Provision staging replicas for testing",
      severity: "High",
      workspace: "infrastructure",
      owner: "DevOps Pod 3",
      status: "Completed",
      details:
        "Provision and configure duplicate node targets for running E2E build cycles against production-equivalent db locks.",
      createdAt: "2026-06-27T10:00:00Z",
      completedAt: "2026-06-27T12:00:00Z",
    },
    {
      id: "item-12",
      type: "task",
      title: "Draft release summary blog copy",
      severity: "Low",
      workspace: "marketing",
      owner: "Clara O.",
      status: "Backlog",
      details:
        "Create initial draft for the release blog posts outlining the enterprise compliance update.",
      createdAt: "2026-06-27T13:20:00Z",
    },
    {
      id: "item-13",
      type: "task",
      title: "Conduct monthly ledger reconciliation",
      severity: "Medium",
      workspace: "finance",
      owner: "Finance Team",
      status: "In Progress",
      details:
        "Process cloud invoices and cross-reference with monthly operations allocation thresholds.",
      createdAt: "2026-06-27T13:25:00Z",
    },
    {
      id: "item-14",
      type: "task",
      title: "Update external audit contact list",
      severity: "Low",
      workspace: "legalhr",
      owner: "Diana Prince",
      status: "Completed",
      details:
        "Confirm primary contact emails and schedule access details for external compliance auditor.",
      createdAt: "2026-06-27T10:30:00Z",
      completedAt: "2026-06-27T11:45:00Z",
    },
    {
      id: "item-15",
      type: "issue",
      title: "Color contrast ratio warnings in footer",
      severity: "Medium",
      workspace: "uiux",
      owner: "Elena R.",
      status: "Active",
      details:
        "Footer links contrast ratio falls below WCAG AA requirements on light themes. Redesign with darker colors.",
      createdAt: "2026-06-27T13:30:00Z",
    },
    {
      id: "item-16",
      type: "issue",
      title: "Memory leak in pipeline logs buffer stream",
      severity: "High",
      workspace: "engineering",
      owner: "Marcus A.",
      status: "Active",
      details:
        "Buffer array retains old stream log logs even after runs conclude, causing gradual memory leaks in long-running processes.",
      createdAt: "2026-06-27T13:35:00Z",
    },
    {
      id: "item-17",
      type: "issue",
      title: "Frankfurt-ingress-03 pod replication loop",
      severity: "Critical",
      workspace: "infrastructure",
      owner: "DevOps Pod 3",
      status: "Active",
      details:
        "Kubernetes ingress node triggers failure loop under massive request spikes. Auto-eviction thresholds are too low.",
      createdAt: "2026-06-27T13:40:00Z",
    },
    {
      id: "item-18",
      type: "handoff",
      title: "Sync exported theme JSON tokens to repo",
      severity: "Medium",
      workspace: "uiux",
      owner: "Elena R.",
      status: "Active",
      details:
        "Figma tokens are exported and clean. Handoff to Engineering for integration into the style config builder.",
      targetWorkspace: "engineering",
      createdAt: "2026-06-27T13:45:00Z",
    },
    {
      id: "item-19",
      type: "handoff",
      title: "Verify client analytics code GDPR compliance",
      severity: "High",
      workspace: "marketing",
      owner: "Clara O.",
      status: "Active",
      details:
        "Completed integration script draft. Handoff to Legal & HR team to verify tracker settings are fully GDPR-safe.",
      targetWorkspace: "legalhr",
      createdAt: "2026-06-27T13:50:00Z",
    },
  ],
  blockers: [],
  pipeline: {
    status: "Idle",
    stage: "None",
    progress: 0,
    logs: ["[System] System ready. Waiting for trigger..."],
    lastDuration: "4m 12s",
    coverage: 84.2,
    buildCount: 142,
  },
  techStack: [
    {
      name: "React SPA Client",
      status: "Healthy",
      version: "v18.3.1",
      memory: "42MB",
      uptime: "99.99%",
    },
    {
      name: "Tailwind Design compiler",
      status: "Healthy",
      version: "v3.4.4",
      memory: "18MB",
      uptime: "100.00%",
    },
    {
      name: "Docker Gateway Slots",
      status: "Warning",
      version: "v26.1.3",
      memory: "1.2GB",
      uptime: "99.92%",
    },
    {
      name: "Node Core API Engine",
      status: "Healthy",
      version: "v20.12.2",
      memory: "240MB",
      uptime: "99.98%",
    },
  ],
  clusterNodes: [
    {
      name: "us-east-core-01",
      region: "US-East (N. Virginia)",
      status: "Active",
      cpu: 64,
      ram: 78,
      disk: 42,
      host: "aws-ec2-m6g.2xlarge",
    },
    {
      name: "us-west-api-02",
      region: "US-West (Oregon)",
      status: "Active",
      cpu: 32,
      ram: 54,
      disk: 18,
      host: "aws-ec2-c6g.xlarge",
    },
    {
      name: "eu-central-ingress-03",
      region: "EU-Central (Frankfurt)",
      status: "Active",
      cpu: 89,
      ram: 91,
      disk: 67,
      host: "aws-ec2-m6g.2xlarge",
    },
  ],
  uiuxView: {
    activeDevice: "desktop",
    scale: 100,
    activeTab: "components",
    activePage: "PMAS Enterprise Shell v1.4",
    designSystemAlignment: 94.6,
  },
  uiux: {
    tokens: {
      typography: {
        "font-sans-title": {
          fontFamily: "'Inter', sans-serif",
          fontWeight: "700",
          fontSize: "1.25rem",
          lineHeight: "1.4",
        },
        "font-sans-body": {
          fontFamily: "'Inter', sans-serif",
          fontWeight: "400",
          fontSize: "0.875rem",
          lineHeight: "1.5",
        },
        "font-mono-numbers": {
          fontFamily: "'JetBrains Mono', monospace",
          fontWeight: "500",
          fontSize: "1.75rem",
          lineHeight: "1.2",
        },
        "font-mono-logs": {
          fontFamily: "'JetBrains Mono', monospace",
          fontWeight: "400",
          fontSize: "0.75rem",
          lineHeight: "1.6",
        },
      },
      colors: {
        "bg-surface": "#06070a",
        "bg-surface-container": "#0c0e16",
        "color-primary": "#6366f1",
        "color-success": "#10b981",
        "border-outline-variant": "rgba(99, 102, 241, 0.25)",
      },
    },
    assets: [
      {
        name: "logo-dark.svg",
        size: "1.4 KB",
        cdnStatus: "Live",
        date: "Jul 01, 2026",
      },
      {
        name: "avatar-placeholder.png",
        size: "3.8 KB",
        cdnStatus: "Live",
        date: "Jul 02, 2026",
      },
      {
        name: "hero-banner-illustration.svg",
        size: "24.5 KB",
        cdnStatus: "Pending Sync",
        date: "Jul 03, 2026",
      },
      {
        name: "font-subset-inter.woff2",
        size: "12.0 KB",
        cdnStatus: "Live",
        date: "Jul 05, 2026",
      },
    ],
  },
  finance: {
    capex: 1250000,
    opex: 750000,
    burnRate: 165000,
    forecastQ3: 2100000,
    actualQ2: 1980000,
  },
  marketing: {
    campaigns: [
      {
        name: "Enterprise Lead-Gen Google Search",
        leads: 14200,
        conversion: 2.1,
        spend: 45000,
        status: "Active",
      },
      {
        name: "Product Architecture Whitepaper",
        leads: 8300,
        conversion: 4.8,
        spend: 28000,
        status: "Active",
      },
      {
        name: "SysOps Global Conf Sponsorship",
        leads: 1200,
        conversion: 9.2,
        spend: 85000,
        status: "Completed",
      },
      {
        name: "DevOps Weekly Newsletter Programmatic",
        leads: 4900,
        conversion: 1.5,
        spend: 12000,
        status: "Paused",
      },
    ],
  },
};
