package models

import (
	"encoding/json"
	"time"
)

// Subsystem represents a functional unit or workspace in the system ledger.
type Subsystem struct {
	ID             int    `json:"id" db:"id"`
	Name           string `json:"name" db:"name"`
	Slug           string `json:"slug" db:"slug"`
	Status         string `json:"status" db:"status"` // 'healthy', 'warning', 'blocked'
	LoadPercentage int    `json:"load_percentage" db:"load_percentage"`
}

// TeamMember represents human resources assigned to subsystem workflows.
type TeamMember struct {
	ID             int      `json:"id" db:"id"`
	Name           string   `json:"name" db:"name"`
	AvatarURL      *string  `json:"avatar_url" db:"avatar_url"`
	Role           string   `json:"role" db:"role"`
	SubsystemID    *int     `json:"subsystem_id" db:"subsystem_id"`
	CapacityWeight float64  `json:"capacity_weight" db:"capacity_weight"`
}

// OperationalItem represents telemetry tickets: tasks, blockers, issues, handoffs.
type OperationalItem struct {
	ID                int        `json:"id" db:"id"`
	TicketCode        string     `json:"ticket_code" db:"ticket_code"`
	Title             string     `json:"title" db:"title"`
	Description       *string    `json:"description" db:"description"`
	Type              string     `json:"type" db:"type"` // 'task', 'blocker', 'issue', 'handoff'
	Severity          string     `json:"severity" db:"severity"` // 'Critical', 'High', 'Medium', 'Low'
	Status            string     `json:"status" db:"status"` // 'Blocked', 'In Progress', 'Completed', 'Backlog', 'Active', 'Resolved'
	OriginSubsystemID *int       `json:"origin_subsystem_id" db:"origin_subsystem_id"`
	AssignedTo        *string    `json:"assigned_to" db:"assigned_to"`
	LinkedPR          *string    `json:"linked_pr" db:"linked_pr"`
	CreatedAt         time.Time  `json:"created_at" db:"created_at"`
	CompletedAt       *time.Time `json:"completed_at" db:"completed_at"`
}

// GraphEdge represents logical topology relations between subsystems.
type GraphEdge struct {
	ID       int     `json:"id" db:"id"`
	SourceID int     `json:"source_id" db:"source_id"`
	TargetID int     `json:"target_id" db:"target_id"`
	EdgeType string  `json:"edge_type" db:"edge_type"`
	Weight   float64 `json:"weight" db:"weight"`
}

// DesignToken stores Figma typography/color design metadata as raw JSON.
type DesignToken struct {
	ID        int             `json:"id" db:"id"`
	Category  string          `json:"category" db:"category"` // 'typography', 'colors'
	TokenData json.RawMessage `json:"token_data" db:"token_data"`
}

// UIAsset monitors high-fidelity assets synced to the CDN.
type UIAsset struct {
	ID        int    `json:"id" db:"id"`
	Name      string `json:"name" db:"name"`
	Size      string `json:"size" db:"size"`
	CDNStatus string `json:"cdn_status" db:"cdn_status"` // 'Live', 'Pending Sync', 'Syncing...'
	Date      string `json:"date" db:"date"`
}

// MarketingCampaign links campaign conversions with engineering dependencies.
type MarketingCampaign struct {
	ID                    int     `json:"id" db:"id"`
	Name                  string  `json:"name" db:"name"`
	Leads                 int     `json:"leads" db:"leads"`
	Conversion            float64 `json:"conversion" db:"conversion"`
	Spend                 float64 `json:"spend" db:"spend"`
	Status                string  `json:"status" db:"status"`
	DependentSubsystemID  *int    `json:"dependent_subsystem_id" db:"dependent_subsystem_id"`
	DependentSubsysStatus string  `json:"dependent_subsystem_status,omitempty"` // populated during joins
}

// =========================================================================
// API payload definitions
// =========================================================================

// TopologyNode represents a node in the graph layout (subsystem or team member).
type TopologyNode struct {
	ID        string      `json:"id"`
	Type      string      `json:"type"` // 'subsystem' or 'member'
	Label     string      `json:"label"`
	Details   interface{} `json:"details"`
}

// APIGraphEdge represents a JSON-friendly relation using node identifiers for the frontend.
type APIGraphEdge struct {
	ID       int     `json:"id"`
	From     string  `json:"from"`
	To       string  `json:"to"`
	EdgeType string  `json:"edge_type"`
	Weight   float64 `json:"weight"`
}

// TopologyResponse represents the unified graph network topology response.
type TopologyResponse struct {
	Nodes []TopologyNode `json:"nodes"`
	Edges []APIGraphEdge `json:"edges"`
}

// AssetPushRequest is the payload sent when syncing asset state.
type AssetPushRequest struct {
	AssetName string `json:"asset_name"`
}

// PipelineTriggerRequest defines the CI/CD compilation request target.
type PipelineTriggerRequest struct {
	SubsystemID int `json:"subsystem_id"`
}

// RCADetails describes compiler failure logs automatically generated by PMAS.
type RCADetails struct {
	BlockerTicket string  `json:"blocker_ticket"`
	Summary       string  `json:"summary"`
	RootCause     string  `json:"root_cause"`
	Remediation   string  `json:"remediation"`
	AIConfidence  float64 `json:"ai_confidence"`
}

// PipelineTriggerResponse handles compilation status returns.
type PipelineTriggerResponse struct {
	Status    string      `json:"status"` // 'Success', 'Failed'
	Message   string      `json:"message"`
	RCA       *RCADetails `json:"rca,omitempty"`
}

// OperationsResolveRequest executes cascading transactional status resolutions.
type OperationsResolveRequest struct {
	TicketCode string `json:"ticket_code"`
}

// Credential represents API or database credentials used in the application.
type Credential struct {
	ID          int       `json:"id" db:"id"`
	Name        string    `json:"name" db:"name"`
	Value       string    `json:"value" db:"value"`
	Description string    `json:"description" db:"description"`
	UpdatedAt   time.Time `json:"updated_at" db:"updated_at"`
}

// CredentialSaveRequest is the payload sent when creating or updating credentials.
type CredentialSaveRequest struct {
	Name        string `json:"name"`
	Value       string `json:"value"`
	Description string `json:"description"`
}

